#!/usr/bin/env bash
#Script displays a different info for 9th iteration
n=1
while [ $n -le 10 ]
do
        echo "Best School"
        if [ $n -eq 9 ]
        then
                echo "Hi"
        fi
        ((++n))
done
