#!/usr/bin/env bash
#Script displays a different info for 4th and 8th iterations

i=1
while [ $i -le 10 ]; do
	if [ $i == 4 ]; then
		echo bad luck
	elif [ $i == 8 ]; then
		echo good luck
	else
	    echo Best School
	fi
	((i += 1))
done
